# Generated by Django 4.2.7 on 2025-02-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveauEtude', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('BE', 'Beginner'), ('MD', 'Medium'), ('HI', 'High')], default='BE', max_length=2)),
            ],
        ),
    ]
