# Generated by Django 4.2.7 on 2025-02-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeApp', '0002_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='niveauEtude',
            field=models.IntegerField(max_length=200),
        ),
    ]
