# Generated by Django 4.2.7 on 2025-02-23 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeApp', '0003_alter_child_niveauetude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='niveauEtude',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
